<a href="https://colab.research.google.com/github/mrbedoya/ml-2026/blob/main/11_ArbolesDecisionRandomForestClasificacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Árboles de Decisión Random Forest (Clasificación)

## 1. Librerias y configuraciones previas

In [1]:
# Tratamiento de datos
# ==============================================================================
import pandas as pd
import numpy as np

# Almacenar en caché los resultados de funciones en el disco
# ==============================================================================
import joblib

# Gestion de librerias
# ==============================================================================
from importlib import reload

# Matemáticas y estadísticas
# ==============================================================================
import math

# Preprocesado y modelado
# ==============================================================================

#Separar los datos entrenamiento y prueba
from sklearn.model_selection import train_test_split

#Escalar Variables
from sklearn.preprocessing import MinMaxScaler

#Configuracion de hiperparámetros
from sklearn.model_selection import ParameterGrid, GridSearchCV

#Creación de modelo
from sklearn.ensemble import RandomForestClassifier

# Evaluación del modelo
from sklearn.metrics import classification_report

# Gráficos
# ==============================================================================
import matplotlib.pyplot as plt
from matplotlib import style
import seaborn as sns

# Interuactuar con os y solicitudes desde HTTP
# ==============================================================================
import os
import sys
import requests

# Configuración warnings
# ==============================================================================
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Parametros globales
# ==============================================================================

# URL base de GitHub para el repositorio
GITHUB_BASE_URL = 'https://raw.githubusercontent.com/mrbedoya/ml-2026/main/'

# Nombres de los archivos requeridos
DATASET_FILE_NAME = '02_GermanCredit_Prep.csv'
UTILS_FILE_NAME = 'funciones.py'

# Nombres de los directorios para utilidades, datasets y modelos
DATASETS_PATH = 'datasets/'
UTILS_PATH = 'utils/'
MODELS_PATH = 'modelos/'
MODELS_CLASIFICACION_PATH = os.path.join(MODELS_PATH, 'clasificacion')
MODELS_SCALER_PATH = os.path.join(MODELS_PATH, 'scaler')

# URL completa del dataset y utils en GitHub
github_dataset_url = os.path.join(GITHUB_BASE_URL, DATASETS_PATH, DATASET_FILE_NAME)
github_utils_url = os.path.join(GITHUB_BASE_URL, UTILS_PATH, UTILS_FILE_NAME)

# Rutas locales completas de datasets y utils
local_dataset_path = os.path.join(DATASETS_PATH, DATASET_FILE_NAME)
local_utils_path = os.path.join(UTILS_PATH, UTILS_FILE_NAME)

In [3]:
## Cargar datos desde Google Drive
## ==============================================================================

#from google.colab import drive

## Montar Google Drive
#drive.mount('/gdrive')

## Establece el directorio de trabajo dentro de directorio espefíficado en Google Drive
#os.chdir("/gdrive/MyDrive/01_Academia/02_Cursos/20260401_ApredinzajeAutomáticoI_UdeA/")

## Listar archivos de directorio
##!ls

In [4]:
# Funcion local para la carga de archivos
# ==============================================================================

def download_file(url, path, description):
    '''
    Descarga un archivo desde una URL y lo guarda localmente.

    Args:
        url (str): URL del archivo
        path (str): Ruta local de destino
        description (str): Descripción del archivo
    Returns:
        None
    '''
    print(f"Descargando {description} desde: {url}")

    # Realiza una solicitud HTTP GET a la URL proporcionada
    response = requests.get(url)

    # Lanza una excepción si la descarga falla (código de estado HTTP no 200)
    response.raise_for_status()

    # Abre el archivo local en modo de escritura binaria ('wb')
    with open(path, 'wb') as f:
        # Escribe el contenido binario de la respuesta HTTP en el archivo local
        f.write(response.content)

    # Imprime un mensaje confirmando que la descarga fue exitosa y la ruta de guardado
    print(f"{description} descargado exitosamente a: {path}")

In [5]:
## Configuración entorno Colab
# ==============================================================================

# Creación de directorios locales
os.makedirs(DATASETS_PATH, exist_ok=True)
os.makedirs(UTILS_PATH, exist_ok=True)
os.makedirs(MODELS_PATH, exist_ok=True)

# Crear subdirectorios específicos para modelos y escalados
os.makedirs(MODELS_CLASIFICACION_PATH, exist_ok=True)
os.makedirs(MODELS_SCALER_PATH, exist_ok=True)

# Descarga de archivos
download_file(github_dataset_url, local_dataset_path, "dataset")
download_file(github_utils_url, local_utils_path, "funciones")

Descargando dataset desde: https://raw.githubusercontent.com/mrbedoya/ml-2026/main/datasets/02_GermanCredit_Prep.csv
dataset descargado exitosamente a: datasets/02_GermanCredit_Prep.csv
Descargando funciones desde: https://raw.githubusercontent.com/mrbedoya/ml-2026/main/utils/funciones.py
funciones descargado exitosamente a: utils/funciones.py

## 2. Funciones

In [6]:
## Funciones externas
# ==============================================================================

## Añade la ruta definida en 'UTILS_PATH' al 'sys.path' para que Python pueda encontrar módulos
#sys.path.append(UTILS_PATH)

## Importa Funciones externas
#from funciones import multiple_plot, plot_roc_curve

## 3. Carga del dataset

In [7]:
#Se crea un dataframe d con los datos obtenidos de archivo de entrada
d=pd.read_csv(local_dataset_path)

In [8]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1138 entries, 0 to 1137
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   checking_account_status   1138 non-null   object
 1   loan_duration_mo          1138 non-null   int64
 2   credit_history            1138 non-null   object
 3   purpose                   1138 non-null   object
 4   loan_amount               1138 non-null   int64
 5   savings_account_balance   1138 non-null   object
 6   time_employed_yrs         1138 non-null   object
 7   payment_pcnt_income       1138 non-null   int64
 8   gender_status             1138 non-null   object
 9   other_signators           1138 non-null   object
 10  time_in_residence         1138 non-null   int64
 11  property                  1138 non-null   object
 12  age_yrs                   1138 non-null   int64
 13  other_credit_outstanding  1138 non-null   object
 14  home_ownership            1138 non-null   object
 15  number_loans              1138 non-null   int64
 16  job_category              1138 non-null   object
 17  dependents                1138 non-null   int64
 18  telephone                 1138 non-null   object
 19  foreign_worker            1138 non-null   object
 20  bad_credit                1138 non-null   int64
dtypes: int64(8), object(13)
memory usage: 186.8+ KB

## 4. Visualización de datos

### Variables de entrada

In [9]:
#Lista de variables categóricas
catCols = d.select_dtypes(include = ["object", 'category']).columns.tolist()

d[catCols].head(2)

,checking_account_status,credit_history,purpose,savings_account_balance,time_employed_yrs,gender_status,other_signators,property,other_credit_outstanding,home_ownership,job_category,telephone,foreign_worker
0,< 0 DM,critical account - other non-bank loans,car,< 100 DM,1 - 4 years,female-divorced/separated/married,co-applicant,real estate,none,own,skilled,none,yes
1,< 0 DM,current loans paid,car,< 100 DM,1 - 4 years,male-married/widowed,none,real estate,none,own,unskilled-resident,none,yes

In [10]:
#Lista de variables numéricas

numCols=d.select_dtypes(include = ['float64','float64','int32','int64']).columns.tolist()

d[numCols].head(2)

,loan_duration_mo,loan_amount,payment_pcnt_income,time_in_residence,age_yrs,number_loans,dependents,bad_credit
0,12,3499,3,2,29,2,1,1
1,12,1168,4,3,27,1,1,0

In [11]:
##Visualización de frecuencia de instancias para variables categóricas
#multiple_plot(3, d , catCols, None, 'countplot', 'Frecuencia de instancias para variables categóricas',30)

In [12]:
##Visualización de variables numéricas
#multiple_plot(1, d , numCols, None, 'scatterplot', 'Relación entre las variables numéricas',30)

In [13]:
#Eliminar la variable de salida de la lista de variable numéricas
numCols.remove('bad_credit')

### Variable de salida

In [14]:
# Distriución de la variable de salida

d.groupby('bad_credit').bad_credit.count().sort_values(ascending=False)

bad_credit
0    569
1    569
Name: bad_credit, dtype: int64

In [15]:
##Visualización de la variable de salida
#multiple_plot(1, d , None, 'bad_credit', 'countplot', 'Gráfica de frecuencia de bad Credit',0)

## 5. Transformación de datos

### Creación de variables Dummies

In [16]:
# Aplicación de la función de usuario Dummies: one-hot encoding

d =pd.get_dummies(d, drop_first=1)

d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1138 entries, 0 to 1137
Data columns (total 46 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   loan_duration_mo                                        1138 non-null   int64
 1   loan_amount                                             1138 non-null   int64
 2   payment_pcnt_income                                     1138 non-null   int64
 3   time_in_residence                                       1138 non-null   int64
 4   age_yrs                                                 1138 non-null   int64
 5   number_loans                                            1138 non-null   int64
 6   dependents                                              1138 non-null   int64
 7   bad_credit                                              1138 non-null   int64
 8   checking_account_status_< 0 DM                          1138 non-null   bool
 9   checking_account_status_> 200 DM or salary assignment   1138 non-null   bool
 10  checking_account_status_none                            1138 non-null   bool
 11  credit_history_critical account - other non-bank loans  1138 non-null   bool
 12  credit_history_current loans paid                       1138 non-null   bool
 13  credit_history_no credit - paid                         1138 non-null   bool
 14  credit_history_past payment delays                      1138 non-null   bool
 15  purpose_car                                             1138 non-null   bool
 16  purpose_education                                       1138 non-null   bool
 17  purpose_furniture/equipment                             1138 non-null   bool
 18  purpose_other                                           1138 non-null   bool
 19  purpose_radio/television                                1138 non-null   bool
 20  purpose_repairs                                         1138 non-null   bool
 21  savings_account_balance_500 - 1000 DM                   1138 non-null   bool
 22  savings_account_balance_< 100 DM                        1138 non-null   bool
 23  savings_account_balance_>= 1000 DM                      1138 non-null   bool
 24  savings_account_balance_unknown/none                    1138 non-null   bool
 25  time_employed_yrs_4 - 7 years                           1138 non-null   bool
 26  time_employed_yrs_< 1 year                              1138 non-null   bool
 27  time_employed_yrs_>= 7 years                            1138 non-null   bool
 28  time_employed_yrs_unemployed                            1138 non-null   bool
 29  gender_status_male-divorced/separated                   1138 non-null   bool
 30  gender_status_male-married/widowed                      1138 non-null   bool
 31  gender_status_male-single                               1138 non-null   bool
 32  other_signators_guarantor                               1138 non-null   bool
 33  other_signators_none                                    1138 non-null   bool
 34  property_car or other                                   1138 non-null   bool
 35  property_real estate                                    1138 non-null   bool
 36  property_unknown-none                                   1138 non-null   bool
 37  other_credit_outstanding_none                           1138 non-null   bool
 38  other_credit_outstanding_stores                         1138 non-null   bool
 39  home_ownership_own                                      1138 non-null   bool
 40  home_ownership_rent                                     1138 non-null   bool
 41  job_category_skilled                                    1138 non-null   bool
 42  job_category_unemployed-unskilled-non-resident          1138 non-null   bool
 43  job_category_unskilled-resident                         1138 non-null   bool
 44  telephone_yes                                           1138 non-null   bool
 45  foreign_worker_yes                                      1138 non-null   bool
dtypes: bool(38), int64(8)
memory usage: 113.5 KB

## 6. Creación del modelo

### Dividir el conjunto de datos

In [17]:
#Se establece las variables de entrada 'X' y la variable de salida 'y'

X = d.drop(columns ='bad_credit')
y = d['bad_credit']

# la validación cruzada se realiza sobre todo el dataset
X_Completo = X
y_Completo = y

### Escalar Variables

In [18]:
#Se establecen las variables numéricas a escalar

#Num_vars se le asigna la lista con las variables numerivas para posteriormente escalarlas
num_vars = numCols

print(num_vars)

['loan_duration_mo', 'loan_amount', 'payment_pcnt_income', 'time_in_residence', 'age_yrs', 'number_loans', 'dependents']

In [19]:
#Se establecen las variables numéricas a escalar

#Num_vars se le asigna la lista con las variables numerivas para posteriormente escalarlas
num_vars = numCols

# Se crea un objeto MinMaxScaler
scaler = MinMaxScaler()

# Se escalan los valores del dataset entrenamiento y prueba de las columnas numéricas
X_Completo[num_vars] = scaler.fit_transform(X_Completo[num_vars])

X_Completo[num_vars].head()

,loan_duration_mo,loan_amount,payment_pcnt_income,time_in_residence,age_yrs,number_loans,dependents
0,0.117647,0.235579,0.666667,0.333333,0.166667,0.333333,0.0
1,0.117647,0.061857,1.000000,0.666667,0.129630,0.000000,0.0
2,0.294118,0.148681,1.000000,0.333333,0.166667,0.000000,0.0
3,0.073529,0.078253,1.000000,0.333333,0.111111,0.000000,0.0
4,0.338235,0.616709,0.333333,0.333333,0.129630,0.333333,0.0

In [20]:
# Guardar el scaler

SCALER_FILE_NAME = 'minmaxFull_GermanCredits.pkl'
local_scaler_path = os.path.join(MODELS_SCALER_PATH, SCALER_FILE_NAME)

joblib.dump(scaler,  local_scaler_path)

['modelos/scaler/minmaxFull_GermanCredits.pkl']

### Creación del modelo

#### 6.1 Grid Search basado en out-of-bag score

In [30]:
# Grid de hiperparámetros evaluados
# ==============================================================================
param_grid = ParameterGrid(
                {'n_estimators': [150, 200, 250],
                 'max_features': [5, 7, 9],
                 'max_depth'   : [None, 3, 10, 20],
                 'criterion'   : ['gini', 'entropy']
                }
            )

# Loop para ajustar un modelo con cada combinación de hiperparámetros
# ==============================================================================
resultados = {'params': [], 'oob_accuracy': []}

for params in param_grid:

  modelo = RandomForestClassifier(
              bootstrap=True,
              oob_score    = True,
              n_jobs       = -1,
              random_state = 123,
              ** params
            )

  modelo.fit(X_Completo, y_Completo)


  resultados['params'].append(params)
  resultados['oob_accuracy'].append(modelo.oob_score_)

print("Grid Search completado.")

# Resultados
# ==============================================================================
resultadosDf = pd.DataFrame(resultados)
resultadosDf = pd.concat([resultadosDf, resultadosDf['params'].apply(pd.Series)], axis=1)
resultadosDf = resultadosDf.sort_values('oob_accuracy', ascending=False)
resultadosDf = resultadosDf.drop(columns = 'params')

Grid Search completado.

In [32]:
resultadosDf.head()

    oob_accuracy criterion  max_depth  max_features  n_estimators
64      0.910369   entropy       20.0             5           200
29      0.909490      gini       20.0             5           250
37      0.907733   entropy        NaN             5           200
44      0.907733   entropy        NaN             9           250
65      0.907733   entropy       20.0             5           250

In [35]:
# Obtener los mejores parámetros del DataFrame de resultados OOB
best_oob_params_row = resultadosDf.iloc[0]
best_oob_hyperparameters = {
    'criterion': best_oob_params_row['criterion'],
    'max_depth': int(best_oob_params_row['max_depth']) if pd.notna(best_oob_params_row['max_depth']) else None,
    'max_features': best_oob_params_row['max_features'],
    'n_estimators': best_oob_params_row['n_estimators']
}

# Establecer estos parámetros en modelrf y entrenar el modelo
# Primero, asegurémonos de que 'modelo' sea una instancia de RandomForestClassifier
# Si 'modelo' no está definido o es de otro tipo, necesitamos inicializarlo.
# Asumiendo que 'modelo' fue definido previamente como RandomForestClassifier

# En el caso de que el modelo no haya sido inicializado o se quiera usar uno nuevo
# modelo = RandomForestClassifier(random_state=123) # Ajusta según sea necesario

modelo.set_params(**best_oob_hyperparameters)
modelo.fit(X_Completo, y_Completo)

print("modelrf entrenado con los mejores parámetros de los resultados OOB.")

modelrf entrenado con los mejores parámetros de los resultados OOB.

In [36]:
modelo.score(X_Completo, y_Completo)

1.0

In [ ]:
modelo.set_params(**resultados.iloc[0, :])
modelo.fit(X_Completo, y_Completo)
#

In [27]:
print(**resultados.iloc[0, :1])

AttributeError: 'dict' object has no attribute 'iloc'

In [ ]:
#Se guarda el modelo de Random Forest

MODEL_FILE_NAME = 'RForest_CV.pkl'
local_model_path = os.path.join(MODELS_CLASIFICACION_PATH, MODEL_FILE_NAME)

joblib.dump(modelrf,  local_model_path)

### 8.2 Grid Search basado en validación cruzada

In [23]:
#Definicion del modelo
modelrf = RandomForestClassifier(random_state = 123, oob_score = True)


# Grid de hiperparámetros evaluados

grid_param = {'n_estimators': [100, 120],
                          'max_features': [5, 7, 9, 11],
                          'max_depth'   : [3, 5, 10, 15, 20],
                          'criterion'   : ['gini', 'entropy']
                         }


# definicion de la variable con el número de pliegues
CV = 10

# las metricas sobre las se evaluará el modelo
scoring = 'f1'

# Búsqueda por grid search con validación cruzada
grid_rf = GridSearchCV(
                        estimator  = modelrf,
                        param_grid = grid_param,
                        scoring    = scoring,
                        cv = CV,
                        n_jobs     = - 1,
                        refit      = True,
                        verbose    = 4,
                        return_train_score = True
                       )

grid_rf.fit(X_Completo, y_Completo)

Fitting 10 folds for each of 80 candidates, totalling 800 fits

KeyboardInterrupt:

In [ ]:
# Resultados
# ==============================================================================
resultados = pd.DataFrame(grid_rf.cv_results_)

resultados.filter(regex = '(param*|mean_t|std_t)') \
    .drop(columns = 'params') \
    .sort_values('mean_test_score', ascending = False) \
    .head(100)

In [ ]:
resultados['diff_test_train'] = abs(resultados['mean_test_score'] - resultados['mean_train_score'])

filtered_results = resultados[resultados['diff_test_train'] <= 0.10]

filtered_results.filter(regex = '(param*|mean_t|std_t|diff_test_train)') \
    .drop(columns = 'params') \
    .sort_values(by=['mean_test_score'], ascending = [False]) \
    .head(10)

In [ ]:
# Obtener los resultados del grid search
results_grid_rf = pd.DataFrame(grid_rf.cv_results_)

# Seleccionar las columnas deseadas
columns_grid_rf = ['param_criterion'] + \
                ['param_max_depth'] + \
                ['param_max_features'] + \
                ['param_n_estimators'] + \
                ['mean_test_score', 'std_test_score', 'mean_train_score']  + \
                [f'split{i}_test_score' for i in range(CV)]

# Filtrar y mostrar los resultados
results_grid_rf_filtered = results_grid_rf[columns_grid_rf]

# Crear la columna scoreWithStd: f1 / std
results_grid_rf_filtered['scoreWithStd'] = results_grid_rf_filtered.apply(
    lambda row: (row['mean_test_score']) / (row['std_test_score']) if row['std_test_score'] != 0 else 0,
    axis=1
)

# Crear la columna diff_test_train: mean_test_score - mean_train_score

results_grid_rf_filtered['diff_test_train'] = abs(
    results_grid_rf_filtered['mean_test_score'] -
    results_grid_rf_filtered['mean_train_score']
)


# Evitar sobreajuste: Filtrar para mostrar solo los resultados donde diff_test_train es menor o igual al 5%
filtered_results = results_grid_rf_filtered[results_grid_rf_filtered['diff_test_train'] <= 0.05]

# Encuentra el índice del máximo valor en la columna scoreWithStd
indice_max_scoreWithStd = results_grid_rf_filtered['scoreWithStd'].idxmax()

# Mostrar los scores promedios por cada parámetro
results_grid_rf_filtered[['param_criterion','param_max_depth','param_max_features','param_n_estimators', 'mean_test_score', 'std_test_score', 'scoreWithStd', 'diff_test_train']]

In [ ]:
# Top 3 de los mejores scores
results_grid_rf_filtered.sort_values(by='scoreWithStd', ascending=False).head(10)[
    ['param_criterion','param_max_depth','param_max_features','param_n_estimators'
     , 'mean_test_score', 'std_test_score', 'scoreWithStd']]

In [ ]:
# Seleccionar el registro correspondiente al índice máximo
registro_max_scoreWithStd = results_grid_rf_filtered.loc[indice_max_scoreWithStd]

registro_max_scoreWithStd.transpose()

In [ ]:
results_grid_rf_filtered.loc[indice_max_scoreWithStd]['mean_test_score']

In [ ]:
# Usar los mejores parámetros para crear el modelo
modelrf.set_params(criterion = results_grid_rf_filtered.loc[indice_max_scoreWithStd]['param_criterion']
                        , max_depth = results_grid_rf_filtered.loc[indice_max_scoreWithStd]['param_max_depth']
                        , max_features = results_grid_rf_filtered.loc[indice_max_scoreWithStd]['param_max_features']
                        , n_estimators = results_grid_rf_filtered.loc[indice_max_scoreWithStd]['param_n_estimators'])

modelrf.fit(X_Completo, y_Completo)

### Guardar modelo

In [ ]:
#Se guarda el modelo de Random Forest

MODEL_FILE_NAME = 'RForest_CV.pkl'
local_model_path = os.path.join(MODELS_CLASIFICACION_PATH, MODEL_FILE_NAME)

joblib.dump(modelrf,  local_model_path)

### Importancia de predictores

#### Importancia por pureza de nodos

In [ ]:
importancia_predictores = pd.DataFrame(
                            {'predictor': X_Completo.columns,
                             'importancia': modelrf.feature_importances_}
                            )
print("Importancia de los predictores en el modelo")
print("-------------------------------------------")
importancia_predictores.sort_values('importancia', ascending=False).head(10)

### Predicción de probabilidades

In [ ]:
# Predicción de probabilidades
# ==============================================================================
predicciones = modelrf.predict_proba(X = X_Completo)
predicciones[:5, :]

In [ ]:
# Clasificación empleando la clase de mayor probabilidad
# ==============================================================================
df_predicciones = pd.DataFrame(data=predicciones, columns=['0', '1'])
df_predicciones['clasificacion_default_0.5'] = np.where(df_predicciones['0'] > df_predicciones['1'], 0, 1)
df_predicciones.head(5)

In [ ]:
# Clasificación final empleando un threshold de 0.8 para la clase 1.
# ==============================================================================
df_predicciones['clasificacion_custom_0.8'] = np.where(df_predicciones['1'] > 0.8, 1, 0)
df_predicciones.iloc[4:10, :]

#### Referencias


- Random Forest
    - https://www.cienciadedatos.net/documentos/py08_random_forest_python.html
    - https://fhernanb.github.io/libro_mod_pred/rand-forests.html
    - https://quantdare.com/decision-trees-gini-vs-entropy/